---
- hosts: localhost
  collections:
    - shipilovds.workstation
  vars_files:
    - vars/general.yml
    - vars/enctypted.yml
  roles:
    - role: pkgs
      tags: ['pkgs']
    - role: tools
      tags: ['tools']
    - role: gnome
      tags: ['gnome']
    - role: services
      tags: ['services']
